---
# tasks file for ansible-gitlab-runner
- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: config.yml
  when:
    - gitlab_runner_config['configure']|bool

- include_tasks: users.yml
